/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.docs.wordlibapp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WordlibData service. Represents a row in the &quot;WLA_WordlibData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.docs.wordlibapp.model.impl.WordlibDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.docs.wordlibapp.model.impl.WordlibDataImpl}.
 * </p>
 *
 * @author mike
 * @see WordlibData
 * @see com.liferay.docs.wordlibapp.model.impl.WordlibDataImpl
 * @see com.liferay.docs.wordlibapp.model.impl.WordlibDataModelImpl
 * @generated
 */
public interface WordlibDataModel extends BaseModel<WordlibData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wordlib data model instance should use the {@link WordlibData} interface instead.
	 */

	/**
	 * Returns the primary key of this wordlib data.
	 *
	 * @return the primary key of this wordlib data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wordlib data.
	 *
	 * @param primaryKey the primary key of this wordlib data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wordlib ID of this wordlib data.
	 *
	 * @return the wordlib ID of this wordlib data
	 */
	public long getWordlibId();

	/**
	 * Sets the wordlib ID of this wordlib data.
	 *
	 * @param wordlibId the wordlib ID of this wordlib data
	 */
	public void setWordlibId(long wordlibId);

	/**
	 * Returns the group ID of this wordlib data.
	 *
	 * @return the group ID of this wordlib data
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this wordlib data.
	 *
	 * @param groupId the group ID of this wordlib data
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this wordlib data.
	 *
	 * @return the user ID of this wordlib data
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this wordlib data.
	 *
	 * @param userId the user ID of this wordlib data
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wordlib data.
	 *
	 * @return the user uuid of this wordlib data
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this wordlib data.
	 *
	 * @param userUuid the user uuid of this wordlib data
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this wordlib data.
	 *
	 * @return the company ID of this wordlib data
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this wordlib data.
	 *
	 * @param companyId the company ID of this wordlib data
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the image ID of this wordlib data.
	 *
	 * @return the image ID of this wordlib data
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this wordlib data.
	 *
	 * @param imageId the image ID of this wordlib data
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the name of this wordlib data.
	 *
	 * @return the name of this wordlib data
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this wordlib data.
	 *
	 * @param name the name of this wordlib data
	 */
	public void setName(String name);

	/**
	 * Returns the person of this wordlib data.
	 *
	 * @return the person of this wordlib data
	 */
	@AutoEscape
	public String getPerson();

	/**
	 * Sets the person of this wordlib data.
	 *
	 * @param person the person of this wordlib data
	 */
	public void setPerson(String person);

	/**
	 * Returns the place of this wordlib data.
	 *
	 * @return the place of this wordlib data
	 */
	@AutoEscape
	public String getPlace();

	/**
	 * Sets the place of this wordlib data.
	 *
	 * @param place the place of this wordlib data
	 */
	public void setPlace(String place);

	/**
	 * Returns the adjective of this wordlib data.
	 *
	 * @return the adjective of this wordlib data
	 */
	@AutoEscape
	public String getAdjective();

	/**
	 * Sets the adjective of this wordlib data.
	 *
	 * @param adjective the adjective of this wordlib data
	 */
	public void setAdjective(String adjective);

	/**
	 * Returns the animal of this wordlib data.
	 *
	 * @return the animal of this wordlib data
	 */
	@AutoEscape
	public String getAnimal();

	/**
	 * Sets the animal of this wordlib data.
	 *
	 * @param animal the animal of this wordlib data
	 */
	public void setAnimal(String animal);

	/**
	 * Returns the celebrity of this wordlib data.
	 *
	 * @return the celebrity of this wordlib data
	 */
	@AutoEscape
	public String getCelebrity();

	/**
	 * Sets the celebrity of this wordlib data.
	 *
	 * @param celebrity the celebrity of this wordlib data
	 */
	public void setCelebrity(String celebrity);

	/**
	 * Returns the verb of this wordlib data.
	 *
	 * @return the verb of this wordlib data
	 */
	@AutoEscape
	public String getVerb();

	/**
	 * Sets the verb of this wordlib data.
	 *
	 * @param verb the verb of this wordlib data
	 */
	public void setVerb(String verb);

	/**
	 * Returns the adverb of this wordlib data.
	 *
	 * @return the adverb of this wordlib data
	 */
	@AutoEscape
	public String getAdverb();

	/**
	 * Sets the adverb of this wordlib data.
	 *
	 * @param adverb the adverb of this wordlib data
	 */
	public void setAdverb(String adverb);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(WordlibData wordlibData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<WordlibData> toCacheModel();

	@Override
	public WordlibData toEscapedModel();

	@Override
	public WordlibData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}